### ISSUE TITLE
Portal integration as an identity Store

### ISSUE THREAD

**Issue by g3r4n** [Esri/geoportal-server#168]
I've add to my portal somme user from my Active Directory. the account is like user@domain. When i try to log to Geoportal with that user it's not working and i've the error :

    mai 27, 2015 9:33:43 AM com.esri.gpt.framework.security.identity.agp.PortalIdentityAdapter validateOAuthResponseToken
    GRAVE: Error validating OAuth response
    com.esri.gpt.framework.http.HttpClientException: HTTP Request failed: HTTP/1.1 404 Not Found
    at com.esri.gpt.framework.http.HttpClientRequest.execute(Unknown Source)
    at com.esri.gpt.framework.security.identity.agp.PortalIdentityAdapter.executeGetUser(Unknown Source)
    at com.esri.gpt.framework.security.identity.agp.PortalIdentityAdapter.validateOAuthResponseToken(Unknown Source)
    at org.apache.jsp.catalog.identity.oauthResponse_jsp._jspService(oauthResponse_jsp.java:65)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:388)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:313)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:260)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
    at org.apache.coyote.ajp.AjpAprProcessor.process(AjpAprProcessor.java:450)
    at org.apache.coyote.ajp.AjpAprProtocol$AjpConnectionHandler.process(AjpAprProtocol.java:403)
    at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1778)
    at java.lang.Thread.run(Thread.java:745)

If I try to log to Geoportal with an account that I create on Portal For ArcGIS,and It Works.
So I presume it’s not possible to use Portal For ArcGIS as an Identity Store if he is configured with an Active Directory?

**Comment by g3r4n** [comment]
th request url is like : 
https://<portal-url>/arcgis/sharing/rest/community/users/<user>%2540<domain>
whereas it has to be : 
https://<portal-url>/arcgis/sharing/rest/community/users/<user>%40<domain>
