### ISSUE TITLE
Manage User Roles

### ISSUE THREAD

**Issue by g3r4n** [Esri/geoportal-server#171]
I have the following error when i search users by username in Administration -> User

Log in the Geportal application : 
    RequestError: Unable to load /geoportal/rest/identity/users/search?q=*&dojo.preventCache=1433337760757 status: 500

Log in console :
    java.lang.NullPointerException
    at com.esri.gpt.server.identity.ManageUserServlet.buildUsersList(ManageUserServlet.java:825)
    at com.esri.gpt.server.identity.ManageUserServlet.serializeUsersAsJson(ManageUserServlet.java:667)
    at com.esri.gpt.server.identity.ManageUserServlet.executeSearch(ManageUserServlet.java:316)
    at com.esri.gpt.server.identity.ManageUserServlet.execute(ManageUserServlet.java:124)
    at com.esri.gpt.framework.context.BaseServlet.doPost(BaseServlet.java:132)
    at com.esri.gpt.framework.context.BaseServlet.doGet(BaseServlet.java:95)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:606)
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
    at java.lang.Thread.run(Thread.java:662)

**Comment by mhogeweg** [comment]
do you use LDAP or Simple authentication adapter?

**Comment by g3r4n** [comment]
I use portal as an identity store.

**Comment by zguo** [comment]
currently the administration > user page only works with LDAP.

**Comment by rajk1** [comment]
I ran into a similar issue while using Microsoft Active Directory. I can see the users but when I click on a user name I run into an error message like the following:

> RequestError: Unable to load /geoportal/rest/identity/users/cn%3D{users details removed}/profile?dojo.preventCache=1462373243638 status: 500

Screenshot below. Is this a bug?

Thanks.

![gp_issue01](https://cloud.githubusercontent.com/assets/17202868/15018447/94cb9740-11e7-11e6-8d8d-21bb229a38c4.png)
