### ISSUE TITLE
ERROR org.xml.sax.SAXParseException: schema_reference.4: Failed to read schema document 

### ISSUE THREAD

**Issue by shamnas8vdk** [Esri/geoportal-server#325]
Getting below error while deploying Geoportal catalog in an internet separated machine 

2020-05-21 13:29:54,770 WARN [org.springframework.beans.factory.xml.XmlBeanDefinitionReader] - Ignored XML validation warning
org.xml.sax.SAXParseException: schema_reference.4: Failed to read schema document 'http://www.springframework.org/schema/security/spring-security.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source) ~[?:1.8.0_251]
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.warning(Unknown Source) [?:1.8.0_251]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source) [?:1.8.0_251]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source) [?:1.8.0_251]
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(Unknown Source) [?:1.8.0_251]
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaWarning(Unknown Source) [?:1.8.0_251]
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument1(Unknown Source) [?:1.8.0_251]
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument(Unknown Source) [?:1.8.0_251]
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(Unknown Source) [?:1.8.0_251]
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(Unknown Source) [?:1.8.0_251]
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.findSchemaGrammar(Unknown Source) [?:1.8.0_251]
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(Unknown Source) [?:1.8.0_251]
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(Unknown Source) [?:1.8.0_251]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source) [?:1.8.0_251]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source) [?:1.8.0_251]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source) [?:1.8.0_251]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source) [?:1.8.0_251]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) [?:1.8.0_251]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source) [?:1.8.0_251]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source) [?:1.8.0_251]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source) [?:1.8.0_251]
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source) [?:1.8.0_251]
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source) [?:1.8.0_251]
	at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:77) [spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

**Comment by mhogeweg** [comment]
ticket moved to correct repo: https://github.com/Esri/geoportal-server-catalog/issues/324
